# Generated by Django 4.0.4 on 2022-05-05 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
