# Generated by Django 4.0.4 on 2022-05-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_checkup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet',
            name='pet',
        ),
        migrations.AddField(
            model_name='vet',
            name='pet',
            field=models.ManyToManyField(to='main_app.pet'),
        ),
    ]
