# Generated by Django 4.0.4 on 2022-05-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_checkup_options_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
