# Generated by Django 4.0.4 on 2022-05-02 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.pet'),
            preserve_default=False,
        ),
    ]
