# Generated by Django 4.0.4 on 2022-05-06 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_remove_vet_pet_vet_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='pet',
            name='prescriptions',
            field=models.ManyToManyField(blank=True, to='main_app.prescription'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='pet',
            field=models.ManyToManyField(blank=True, to='main_app.pet'),
        ),
    ]
