# Generated by Django 4.0.4 on 2022-05-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='checkup',
        ),
    ]
