# Generated by Django 4.0.4 on 2022-05-02 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_pet_url_remove_photo_checkup'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='checkup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.checkup'),
            preserve_default=False,
        ),
    ]
