# Generated by Django 4.0.4 on 2022-05-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_photo_checkup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='checkup',
        ),
    ]
