# Generated by Django 4.0.4 on 2022-05-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_photo_checkup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('refills', models.CharField(max_length=100)),
                ('pet', models.ManyToManyField(to='main_app.pet')),
            ],
        ),
    ]
