# Generated by Django 4.0.4 on 2022-05-04 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_prescriptions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescriptions',
        ),
    ]
