# Generated by Django 4.0.4 on 2022-05-04 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_delete_prescriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckupPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.checkup')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pet')),
            ],
        ),
    ]
