# Generated by Django 4.0.4 on 2022-05-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_checkupphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
