# Generated by Django 4.0.4 on 2022-05-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_prescriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptions',
            name='pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='prescriptions',
            field=models.ManyToManyField(to='main_app.prescriptions'),
        ),
    ]
