# Generated by Django 4.0.4 on 2022-05-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_rename_prescriptions_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkupphoto',
            name='pet',
        ),
    ]
